#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Marker {
    SOI,
    EOI,
    SOS,
    DQT,
    DHT,
    DRI,
    SOF0,
    SOF1,
    SOF2,
    SOF3,
    SOF5,
    SOF6,
    SOF7,
    SOF9,
    SOF10,
    SOF11,
    SOF13,
    SOF14,
    SOF15,
    APP(u8),
    COM,
    RST(u8),
    JPG(u8),
    Other(u16),
}

impl Marker {
    pub fn from_u16(b: u16) -> Self {
        match b {
            0xFFD8 => Marker::SOI,
            0xFFD9 => Marker::EOI,
            0xFFDA => Marker::SOS,
            0xFFDB => Marker::DQT,
            0xFFC4 => Marker::DHT,
            0xFFDD => Marker::DRI,
            0xFFC0 => Marker::SOF0,
            0xFFC1 => Marker::SOF1,
            0xFFC2 => Marker::SOF2,
            0xFFC3 => Marker::SOF3,
            0xFFC5 => Marker::SOF5,
            0xFFC6 => Marker::SOF6,
            0xFFC7 => Marker::SOF7,
            0xFFC9 => Marker::SOF9,
            0xFFCA => Marker::SOF10,
            0xFFCB => Marker::SOF11,
            0xFFCD => Marker::SOF13,
            0xFFCE => Marker::SOF14,
            0xFFCF => Marker::SOF15,
            0xFFD0..=0xFFD7 => Marker::RST((b & 0x7) as u8),
            0xFFE0..=0xFFEF => Marker::APP((b & 0xF) as u8),
            0xFFF0..=0xFFFD => Marker::JPG((b & 0xF) as u8),
            0xFFFE => Marker::COM,
            other => Marker::Other(other),
        }
    }

    pub fn to_u16(self) -> u16 {
        match self {
            Marker::SOI => 0xFFD8,
            Marker::EOI => 0xFFD9,
            Marker::SOS => 0xFFDA,
            Marker::DQT => 0xFFDB,
            Marker::DHT => 0xFFC4,
            Marker::DRI => 0xFFDD,
            Marker::SOF0 => 0xFFC0,
            Marker::SOF1 => 0xFFC1,
            Marker::SOF2 => 0xFFC2,
            Marker::SOF3 => 0xFFC3,
            Marker::SOF5 => 0xFFC5,
            Marker::SOF6 => 0xFFC6,
            Marker::SOF7 => 0xFFC7,
            Marker::SOF9 => 0xFFC9,
            Marker::SOF10 => 0xFFCA,
            Marker::SOF11 => 0xFFCB,
            Marker::SOF13 => 0xFFCD,
            Marker::SOF14 => 0xFFCE,
            Marker::SOF15 => 0xFFCF,
            Marker::RST(n) => 0xFFD0 | (n as u16 & 0x7),
            Marker::APP(n) => 0xFFE0 + n as u16,
            Marker::JPG(n) => 0xFFF0 | (n as u16 & 0xF),
            Marker::COM => 0xFFFE,
            Marker::Other(b) => b,
        }
    }
}
