use phf::phf_map;

use crate::core::attribute::{Attribute, Count, ExifType};

pub static TAGS: phf::Map<u16, Attribute> = phf_map! {
    0x0u16 => Attribute {
        tag_name: "GPS tag version",
        field_name: "GPSVersionID",
        fid: 0x0,
        exif_type: ExifType::Byte,
        count: Count::Fixed(4),
    },
    0x1u16 => Attribute {
        tag_name: "North or South Latitude",
        field_name: "GPSLatitudeRef",
        fid: 0x1,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x2u16 => Attribute {
        tag_name: "Latitude",
        field_name: "GPSLatitude",
        fid: 0x2,
        exif_type: ExifType::Rational,
        count: Count::Fixed(3),
    },
    0x3u16 => Attribute {
        tag_name: "East or West Longitude",
        field_name: "GPSLongitudeRef",
        fid: 0x3,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x4u16 => Attribute {
        tag_name: "Longitude",
        field_name: "GPSLongitude",
        fid: 0x4,
        exif_type: ExifType::Rational,
        count: Count::Fixed(3),
    },
    0x5u16 => Attribute {
        tag_name: "Altitude reference",
        field_name: "GPSAltitudeRef",
        fid: 0x5,
        exif_type: ExifType::Byte,
        count: Count::Fixed(1),
    },
    0x6u16 => Attribute {
        tag_name: "Altitude",
        field_name: "GPSAltitude",
        fid: 0x6,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0x7u16 => Attribute {
        tag_name: "GPS time (atomic clock)",
        field_name: "GPSTimeStamp",
        fid: 0x7,
        exif_type: ExifType::Rational,
        count: Count::Fixed(3),
    },
    0x8u16 => Attribute {
        tag_name: "GPS satellites used for measurement",
        field_name: "GPSSatellites",
        fid: 0x8,
        exif_type: ExifType::Ascii,
        count: Count::Variable,
    },
    0x9u16 => Attribute {
        tag_name: "GPS receiver status",
        field_name: "GPSStatus",
        fid: 0x9,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0xAu16 => Attribute {
        tag_name: "GPS measurement mode",
        field_name: "GPSMeasureMode",
        fid: 0xA,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0xBu16 => Attribute {
        tag_name: "Measurement precision",
        field_name: "GPSDOP",
        fid: 0xB,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0xCu16 => Attribute {
        tag_name: "Speed unit",
        field_name: "GPSSpeedRef",
        fid: 0xC,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0xDu16 => Attribute {
        tag_name: "Speed of GPS receiver",
        field_name: "GPSSpeed",
        fid: 0xD,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0xEu16 => Attribute {
        tag_name: "Reference for direction of movement",
        field_name: "GPSTrackRef",
        fid: 0xE,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0xFu16 => Attribute {
        tag_name: "Direction of movement",
        field_name: "GPSTrack",
        fid: 0xF,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0x10u16 => Attribute {
        tag_name: "Reference for direction of image",
        field_name: "GPSImgDirectionRef",
        fid: 0x10,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x11u16 => Attribute {
        tag_name: "Direction of image",
        field_name: "GPSImgDirection",
        fid: 0x11,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0x12u16 => Attribute {
        tag_name: "Geodetic survey data used",
        field_name: "GPSMapDatum",
        fid: 0x12,
        exif_type: ExifType::Ascii,
        count: Count::Variable,
    },
    0x13u16 => Attribute {
        tag_name: "Reference for latitude of destination",
        field_name: "GPSDestLatitudeRef",
        fid: 0x13,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x14u16 => Attribute {
        tag_name: "Latitude of destination",
        field_name: "GPSDestLatitude",
        fid: 0x14,
        exif_type: ExifType::Rational,
        count: Count::Fixed(3),
    },
    0x15u16 => Attribute {
        tag_name: "Reference for longitude of destination",
        field_name: "GPSDestLongitudeRef",
        fid: 0x15,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x16u16 => Attribute {
        tag_name: "Longitude of destination",
        field_name: "GPSDestLongitude",
        fid: 0x16,
        exif_type: ExifType::Rational,
        count: Count::Fixed(3),
    },
    0x17u16 => Attribute {
        tag_name: "Reference for bearing of destination",
        field_name: "GPSDestBearingRef",
        fid: 0x17,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x18u16 => Attribute {
        tag_name: "Bearing of destination",
        field_name: "GPSDestBearing",
        fid: 0x18,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0x19u16 => Attribute {
        tag_name: "Reference for distance to destination",
        field_name: "GPSDestDistanceRef",
        fid: 0x19,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(2),
    },
    0x1Au16 => Attribute {
        tag_name: "Distance to destination",
        field_name: "GPSDestDistance",
        fid: 0x1A,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
    0x1Bu16 => Attribute {
        tag_name: "Name of GPS processing method",
        field_name: "GPSProcessingMethod",
        fid: 0x1B,
        exif_type: ExifType::Undefined,
        count: Count::Variable,
    },
    0x1Cu16 => Attribute {
        tag_name: "Name of GPS area",
        field_name: "GPSAreaInformation",
        fid: 0x1C,
        exif_type: ExifType::Undefined,
        count: Count::Variable,
    },
    0x1Du16 => Attribute {
        tag_name: "GPS date",
        field_name: "GPSDateStamp",
        fid: 0x1D,
        exif_type: ExifType::Ascii,
        count: Count::Fixed(11),
    },
    0x1Eu16 => Attribute {
        tag_name: "GPS differential correction",
        field_name: "GPSDifferential",
        fid: 0x1E,
        exif_type: ExifType::Short,
        count: Count::Fixed(1),
    },
    0x1Fu16 => Attribute {
        tag_name: "Horizontal positioning error",
        field_name: "GPSHPositioningError",
        fid: 0x1F,
        exif_type: ExifType::Rational,
        count: Count::Fixed(1),
    },
};
